export default [
  {
    id: '1',
    title: 'The Da Vinci Code',
    authorId: '1',
    createdAt: '10-05-2019',
    year: 2003,
    image: 'https://i.postimg.cc/zBFwnfPf/unnamed.png',
  },
  {
    id: '2',
    title: 'Fifty Shades of Grey',
    authorId: '2',
    createdAt: '15-05-2019',
    year: 2011,
    image: 'https://i.postimg.cc/zBFwnfPf/unnamed.png',
  },
  {
    id: '3',
    title: 'Angels and Demons',
    authorId: '1',
    createdAt: '2-06-2019',
    year: 2000,
    image: 'https://i.postimg.cc/zBFwnfPf/unnamed.png',
  },
  {
    id: '4',
    title: 'Atonement',
    authorId: '9',
    createdAt: '13-06-2020',
    year: 2001,
    image: 'https://i.postimg.cc/zBFwnfPf/unnamed.png',
  },
  {
    id: '5',
    title: 'Girl with the Dragon Tattoo,The:Millennium Trilogy',
    authorId: '3',
    createdAt: '21-07-2020',
    year: 2005,
    image: 'https://i.postimg.cc/zBFwnfPf/unnamed.png',
  },
  {
    id: '6',
    title: 'The Gruffalo',
    authorId: '7',
    createdAt: '30-07-2020',
    year: 2009,
    image: 'https://i.postimg.cc/zBFwnfPf/unnamed.png',
  },
  {
    id: '7',
    title: 'One Day',
    authorId: '8',
    createdAt: '10-08-2021',
    year: 2009,
    image: 'https://i.postimg.cc/zBFwnfPf/unnamed.png',
  },
  {
    id: '8',
    title: 'The Lovely Bones',
    authorId: '4',
    createdAt: '19-08-2021',
    year: 2002,
    image: 'https://i.postimg.cc/zBFwnfPf/unnamed.png',
  },
  {
    id: '9',
    title: 'The Curious Incident of the Dog in the Night-Time',
    authorId: '5',
    createdAt: '3-09-2021',
    year: 2003,
    image: 'https://i.postimg.cc/zBFwnfPf/unnamed.png',
  },
  {
    id: '10',
    title: 'A Short History of Nearly Everything',
    authorId: '6',
    createdAt: '12-09-2021',
    year: 2003,
    image: 'https://i.postimg.cc/zBFwnfPf/unnamed.png',
  },
];
